FizzBuzzApp/Models/FizzBuzz/FizzBuzzModel.cs
namespace FizzBuzzApp.Models.FizzBuzz
{
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using PagedList;

    /// <summary>
    /// FizzBuzzViewModel for the FizzBuzz Application
    /// </summary>
    public class FizzBuzzModel
    {
        [Required(ErrorMessage = "The value is mandatory.")]
        [DisplayName("Input Value ")]
        [Range(1, 1000, ErrorMessage = "The value should be an integer between 1 and 1000.")]
        public int UserValue { get; set; }

        public IPagedList<string> FizzBuzzList { get; set; }
    }
}

FizzBuzzApp/Controllers/FizzBuzzController.cs
namespace FizzBuzzApp.Controllers
{
    using FizzBuzzApp.BusinessLogic.Interfaces;
    using FizzBuzzApp.Models.FizzBuzz;
    using PagedList;
    using System.Web.Mvc;

    public class FizzBuzzController : Controller
    {
        private const int PAGE_SIZE = 20;
        private readonly IFizzBuzzService fizzBuzzService;

        /// <summary>
        /// Constructor for FizzBuzzController.
        /// </summary>
        /// <param name="service">Service to get FizzBuzz items</param>
        public FizzBuzzController(IFizzBuzzService service)
        {
            this.fizzBuzzService = service;
        }

        /// <summary>
        /// Home
        /// </summary>
        /// <returns>View</returns>
        [HttpGet]
        public ActionResult Home()
        {
            return View("Home");
        }

        /// <summary>
        /// Home
        /// </summary>
        /// <param name="model">FizzBuzz model object</param>
        /// <returns>Home view</returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Home(FizzBuzzModel model)
        {
            if (ModelState.IsValid)
            {
                model.FizzBuzzList = this.GetListByPage(model.UserValue);
                return View("Home", model);
            }

            return View("Home");
        }

        /// <summary>
        /// Navigate to given page number.
        /// </summary>
        /// <param name="value">Input value</param>
        /// <param name="page">Page number</param>
        /// <returns>Home view</returns>
        [HttpGet]
        public ActionResult NavigateToPage(int value, int? page)
        {
            var model = new FizzBuzzModel
            {
                UserValue = value,
                FizzBuzzList = this.GetListByPage(value, page)
            };

            return View("Home", model);
        }

        /// <summary>
        /// Gets FizzBuzz list of items by page.
        /// </summary>
        /// <param name="value">Input value</param>
        /// <param name="page">Page number</param>
        /// <returns>Paged list</returns>
        private IPagedList<string> GetListByPage(int value, int? page = 1)
        {
            return this.fizzBuzzService.GetFizzBuzzItems(value).ToPagedList(page ?? 1, PAGE_SIZE);
        }
    }
}

FizzBuzzApp/Views/FizzBuzz/Home.cshtml
@model FizzBuzzApp.Models.FizzBuzz.FizzBuzzModel

@{
    ViewBag.Title = "FizzBuzzApp";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<h2>FizzBuzzApp</h2>
@using (Html.BeginForm("Home", "FizzBuzz", FormMethod.Post))
{
    @Html.AntiForgeryToken()
    @Html.LabelFor(x => x.UserValue)
    @Html.TextBoxFor(x => x.UserValue)
    @Html.ValidationMessageFor(x => x.UserValue, "",new { @class = "validationError" })
    <p>
        <button type="submit">Submit</button>
    </p>
    <div>
    @if (Model != null && Model.FizzBuzzList != null)
    {
        @Html.Partial("_FizzBuzzList")
    }
    </div>
}

FizzBuzzApp/Views/FizzBuzz/_FizzBuzzList.cshtml
@using PagedList.Mvc
@model FizzBuzzApp.Models.FizzBuzz.FizzBuzzModel
<div>
    <ul>
        @foreach (var item in Model.FizzBuzzList)
        {
            var values = item.Split(' ');
            <li>
                @foreach (var value in values)
                {
                    <span class="@value">@value</span>
                }
            </li>
        }
    </ul>
</div>
<div class="pagination">
    @{
        var options = PagedListRenderOptions.Minimal;
        options.LinkToPreviousPageFormat = "Previous";
        options.LinkToNextPageFormat = "Next";
        @Html.PagedListPager(Model.FizzBuzzList, page => Url.Action("NavigateToPage", new { value = @Model.UserValue, page }), options);
    }
</div>

FizzBuzzApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
</head>
<body>
    @RenderBody()
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/jqueryval")
</body>
</html>